### PR TITLE
update build configs for OSX

### PR DESCRIPTION
**Pull request by ngokevin**

### CODE REVIEW

**Comment by ngokevin** [comment]
Gonna test it a bit more then reopen.

**Comment by avaer** [comment]
FYI the `binding.gyp` is not important here, it's not used for anything. The main action is in `/labsound`.

**Comment by ngokevin** [comment]
On OSX, the built binary is output into `bin/` so the node-gyp build was failing to find it. Not for the purposes of the bug, was just something I ran into.

**Comment by ngokevin** [comment]
Oh, I see. Exokit has its own bindings. But useful for testing at least to have working in the repo. I also updated the cmakefile to get it to compile on MacOS.

**Comment by avaer** [comment]
Yeah the cmake looks like a legitimate fix.

**Pull request closed without merging**
